{% extends request.ajax ? "layout_blank.phtml" : "layout_default.phtml" %}
{% import "macro_functions.phtml" as mf %}
{% block meta_title %}{% trans 'Contact us' %}{% endblock %}

{% set company = guest.system_company %}

{% block content_before %}
		<!-- Page Heading/Breadcrumbs -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">{% trans 'Contact us' %}</h1>
				<ol class="breadcrumb">
					<li><a href="{{''|link }}">{% trans 'Home' %}</a></li>
					<li class="active">{% trans 'Contact us' %}</li>
				</ol>
            </div>
        </div>
        <!-- /.row -->
{% endblock %}
{% block content %}

		<!-- Content Row -->
        <div class="row">
			
            </div>
            <!-- Contact Details Column -->
            <div class="col-md-4">
                <h3>Contact Details</h3>
                <p><i class="fa fa-envelope-o"></i> 
                    E-mail: <a href="mailto:{{ company.email }}">{{ company.email }}</a></p>
                <p><i class="fa fa-globe"></i> 
                    Web: <a href="{{ company.www }}">{{ company.www }}</a></p>
                <p><i class="fa fa-comments-o"></i> 
                    Discord: <a href="https://discord.gg/xe8vkhBwgv">xe8vkhBwgv</a></p>
            </div>
        </div>
        <!-- /.row -->

{% endblock %}