    	<span>&copy; Copyright {{ now|date('Y') }}. All rights reserved. <a href="https://github.com/hostshibe/mercury" target="_blank">Mercury</a>, powered by <a href="http://www.boxbilling.com" title="Billing system" target="_blank">BoxBilling {{ guest.system_version }}</a>
                    <a href="#" title="" id="help_popup_button" style="float:right;">Help</a>
        </span>

        {% block js %}
        <script type="text/javascript">
            document.getElementById('help_popup_button').addEventListener('click',function(e){
                e.preventDefault();
                document.getElementById('help_popup').style.display = 'block';
            });
            document.getElementById('help_popup_close').addEventListener('click',function(e){
                e.preventDefault();
                document.getElementById('help_popup').style.display = 'none';
            });
        </script>
        {% endblock %}